name: cicd-setup-development
on: 
  push:
    branches:
      - "development"
    paths-ignore:
     - '**.md'
jobs:
  tests:
    runs-on: ubuntu-latest
    container: golang:1.15-buster
    services:
      # Label used to access the service container
      redis:
        # Docker Hub image
        image: bitnami/redis:latest
        # Set health checks to wait until redis has started
        env:
          REDIS_PASSWORD: ${{secrets.REDIS_PASSWORD}}
          REDIS_PORT_NUMBER: ${{secrets.REDIS_PORT_NUMBER}}
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps: 
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.0
      - name: run go test
        run: |
            go test ./... -v
        env:
          REDIS_PORT_NUMBER: ${{secrets.REDIS_PORT_NUMBER}}
          REDIS_DSN:  ${{secrets.REDIS_DSN}}
          REDIS_PASSWORD: ${{secrets.REDIS_PASSWORD}}
  build:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          build-args: |
            REDIS_DSN=${{ secrets.REDIS_DSN }}
            REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}
          tags:  "${{secrets.DOCKERHUB_USERNAME}}/${{secrets.IMAGE_NAME}}:latest"