name: cicd

on: 
  push:
    branches:
      - "*"
    paths-ignore:
     - '**.md'
jobs:
  testgithubactions:
    runs-on: ubuntu-latest

    services:
      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps: 
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.0
      - name: run go version
        run: |
            go test ./... -v
        env:
          REDIS_PORT_NUMBER: 6379
          REDIS_DSN: redis:${REDIS_PORT_NUMBER}
          REDIS_PASSWORD: ""
