name: cicd

on: 
  push:
    branches:
      - "*"
    paths-ignore:
     - '**.md'
jobs:
  testgithubactions:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ‘1.15.0-rc1’
      - name: run go version
        run: |
            go version
